# Generated by Django 5.0.2 on 2024-02-13 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default='')),
                ('gateOpens', models.DateTimeField(blank=True, null=True)),
                ('gateCloses', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=500)),
                ('categories', models.CharField(blank=True, max_length=500)),
                ('banner', models.ImageField(blank=True, height_field='100', upload_to='banner', width_field='523')),
                ('secondBanner', models.ImageField(blank=True, height_field='1600', upload_to='secondBanner', width_field='400')),
                ('homePageTopBanner', models.ImageField(blank=True, height_field='1000', upload_to='homePageTopBanner', width_field='523')),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('templateName', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('done', 'Done'), ('canceled', 'Canceled'), ('waiting', 'Waiting'), ('closed', 'Closed'), ('postponed', 'Postponed')], default='None', max_length=50)),
                ('isLive', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('acknowledgement', ckeditor.fields.RichTextField(blank=True)),
                ('ticketPolicy', ckeditor.fields.RichTextField(blank=True)),
                ('eventFaq', ckeditor.fields.RichTextField(blank=True)),
                ('ruleBook', models.FileField(default='', upload_to='allPdf')),
            ],
        ),
    ]
