# Generated by Django 5.0.2 on 2024-02-14 08:09

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mydashboard_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydashboard',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner', validators=[dashboard.models.validateBannerSize]),
        ),
        migrations.AlterField(
            model_name='mydashboard',
            name='homePageTopBanner',
            field=models.ImageField(blank=True, upload_to='homePageTopBanner', validators=[dashboard.models.validateHomePageTopBanner]),
        ),
        migrations.AlterField(
            model_name='mydashboard',
            name='secondBanner',
            field=models.ImageField(blank=True, upload_to='secondBanner', validators=[dashboard.models.validateSecondBanner]),
        ),
    ]
