# Generated by Django 5.0.2 on 2024-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_mydashboard_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydashboard',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('done', 'Done'), ('canceled', 'Canceled'), ('waiting', 'Waiting'), ('closed', 'Closed'), ('postponed', 'Postponed')], max_length=50),
        ),
    ]
