# Generated by Django 5.0.2 on 2024-02-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_mydashboard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('quangtity', models.IntegerField()),
                ('myDashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mydashboard')),
            ],
        ),
    ]
